services:
  database:
    image: '{imageName}'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
    labels:
      org.springframework.boot.jdbc.parameters: 'ApplicationName=spring+boot'
      org.springframework.boot.r2dbc.parameters: 'applicationName=spring boot'
