services:
  database:
    image: '{imageName}'
    ports:
      - '5432'
    environment:
      - 'POSTGRESQL_USERNAME=myuser'
      - 'POSTGRESQL_DATABASE=mydatabase'
      - 'POSTGRESQL_PASSWORD=secret'
